// <auto-generated />
namespace Araretama.BomNaEscolaBomDeBola.DataAccess.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class banco3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(banco3));
        
        string IMigrationMetadata.Id
        {
            get { return "201901290004086_banco3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
